create TABLE EMPLOYEES3 (
 
    EMP_ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(252),
    DEPARTMENT VARCHAR(128),
    SALARY BIGINT,GENDER VARCHAR(128),
    JOINED_ON TIMESTAMP,
    PRIMARY KEY (EMP_ID));
    INSERT INTO EMPLOYEES (EMP_ID, NAME, DEPARTMENT, SALARY, GENDER , JOINED_ON) VALUES (1, 'Nataraja G', 'Documentation', 10000, CURRENT_TIMESTAMP, MALE);
INSERT INTO EMPLOYEES (EMP_ID, NAME, DEPARTMENT, SALARY, GENDER , JOINED_ON) VALUES (2, 'Amar M', 'Entertainment', 12000, CURRENT_TIMESTAMP,MALE);
INSERT INTO EMPLOYEES (EMP_ID, NAME, DEPARTMENT, SALARY, GENDER , JOINED_ON) VALUES (3, 'Nagesh Y', 'Admin', 25000, CURRENT_TIMESTAMP,MALE);
INSERT INTO EMPLOYEES (EMP_ID, NAME, DEPARTMENT, SALARY, GENDER , JOINED_ON) VALUES (4, 'Vasu V', 'Security', 2500, CURRENT_TIMESTAMP,MALE);
select * FROM EMPLOYEES3